"""
Generate HTML docs
Configuration file for the Sphinx documentation builder.
https://www.sphinx-doc.org/en/master/usage/configuration.html
"""

import datetime
import django
import sys
import os

from pathlib import Path
from django.conf import settings

# -- Path setup --------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent
# sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.abspath(BASE_DIR))

# -- Pre-processing Tasks --------------------------------------------------------------
settings.configure()

# -- Project information -----------------------------------------------------
project = 'App'
author = 'Jonas Vieira de Souza'
copyright = '2021, ' + author
year = datetime.date.today().year

# The tag alpha/beta/rc
release_tag ='alpha'

# The short X.Y version.
version = '1.0'

# The full version, including alpha/beta/rc tags
release = version + '-' + release_tag

# -- General configuration ---------------------------------------------------
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx_copybutton',
    'sphinx_sitemap',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx.
language = 'pt_BR'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Options for HTML output -------------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# The theme to use for HTML and HTML Help pages.
html_theme = 'sphinx_rtd_theme'

# configure theme
html_context = {
  'display_github': True,
  'github_user': 'jvsouza',
  'github_repo': 'serviceOfPersistence',
  'github_version': 'master/docs/',
}
html_theme_options = {
    'analytics_id': 'UA-XXXXXXX-1',  #  Provided by Google in your dashboard
    'analytics_anonymize_ip': False,
    'logo_only': True,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}


# html include
html_title = 'app'

# The name of an image file (relative to this directory) to place at the top of the sidebar.
html_logo = '_static/img/favicon-32x32.png'

# The name of an image file (within the static path) to use as favicon of the docs.  
html_favicon = '_static/img/favicon.ico'

# Add any paths that contain custom static files (such as style sheets)
html_static_path = ['_static']

# Output file base name for HTML help builder.
htmlhelp_basename = 'Appdoc'

html_show_sphinx = False
html_show_copyright = False

# add path of file custom css
def setup(app):
  # app.add_css_file('css/bootstrap.min.css')
  app.add_css_file('css/custom.css')

